# Generated by Django 5.1.4 on 2025-03-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sala',
            name='grupos_permitidos',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='usuarios_permitidos',
        ),
        migrations.AddField(
            model_name='sala',
            name='tipo_usuario_permitido',
            field=models.CharField(blank=True, choices=[('ingresso', 'Ingresso'), ('egresso', 'Egresso')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='cursos_permitidos',
            field=models.ManyToManyField(blank=True, related_name='salas', to='forum.curso'),
        ),
    ]
