# Generated by Django 5.1.4 on 2025-03-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
        ('forum', '0002_curso_remove_sala_grupos_permitidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cursos',
            field=models.ManyToManyField(blank=True, to='forum.curso'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tipo_usuario',
            field=models.CharField(choices=[('ingresso', 'Ingresso'), ('egresso', 'Egresso')], default='ingresso', max_length=10),
        ),
    ]
